// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoHASiuVRO21osOII6SZWMd_Dpv1UYcMM',
    appId: '1:86206417952:web:7dc32d4e33b26542ba0045',
    messagingSenderId: '86206417952',
    projectId: 'easyhomecontrol-1',
    authDomain: 'easyhomecontrol-1.firebaseapp.com',
    storageBucket: 'easyhomecontrol-1.firebasestorage.app',
    measurementId: 'G-5GC7V06LQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDEHpA9e5xphYBbX-NYLAWU_FDUgzJLxw',
    appId: '1:86206417952:android:9acfc7426c71ae06ba0045',
    messagingSenderId: '86206417952',
    projectId: 'easyhomecontrol-1',
    databaseURL: 'https://easyhomecontrol-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'easyhomecontrol-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Hf6zSNkuTPPu4wyXPHzzVXQAcaUphf8',
    appId: '1:86206417952:ios:da4868f081ba2565ba0045',
    messagingSenderId: '86206417952',
    projectId: 'easyhomecontrol-1',
    storageBucket: 'easyhomecontrol-1.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeAutomation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Hf6zSNkuTPPu4wyXPHzzVXQAcaUphf8',
    appId: '1:86206417952:ios:da4868f081ba2565ba0045',
    messagingSenderId: '86206417952',
    projectId: 'easyhomecontrol-1',
    storageBucket: 'easyhomecontrol-1.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeAutomation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoHASiuVRO21osOII6SZWMd_Dpv1UYcMM',
    appId: '1:86206417952:web:0ad3bcbf61a14b7cba0045',
    messagingSenderId: '86206417952',
    projectId: 'easyhomecontrol-1',
    authDomain: 'easyhomecontrol-1.firebaseapp.com',
    storageBucket: 'easyhomecontrol-1.firebasestorage.app',
    measurementId: 'G-P5M6GR7RGP',
  );
}
